# Generated by Django 4.2.13 on 2024-06-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_b', models.CharField(max_length=100)),
                ('column_c', models.CharField(max_length=100)),
                ('column_d', models.FloatField()),
                ('column_f', models.CharField(max_length=100)),
            ],
        ),
    ]
