# Generated by Django 4.2.13 on 2024-06-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbOperation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelmodel',
            old_name='column_b',
            new_name='machine_name',
        ),
        migrations.RenameField(
            model_name='excelmodel',
            old_name='column_c',
            new_name='parameter_name',
        ),
        migrations.RenameField(
            model_name='excelmodel',
            old_name='column_d',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='excelmodel',
            old_name='column_f',
            new_name='yesterday_date',
        ),
    ]
